name: ready_to_use_widgets
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.10.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.1.57
  vexana: ^2.8.0
  #state management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.3

  kartal: ^2.3.2

  auto_size_text: ^3.0.0

  image_picker: ^0.8.5+3

  image_cropper: ^2.0.3

  flutter_colorpicker: ^1.0.3

  path: ^1.8.1

  #utility
  internet_connection_checker: ^0.0.1+3
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
